### PR TITLE
CI: OCaml 4.04 .. 4.10

### PR DESCRIPTION
**Pull request by anton-trunov**
Switch to Ubuntu Bionic because it has libsecp256k1 packages
and does not require any PPAs

### CODE REVIEW

**Comment by anton-trunov** [comment]
It looks like CI is not activated for this repo. But it is for my fork and Travis says it's all green: https://travis-ci.com/github/anton-trunov/secp256k1-ml/builds/169189608

**Comment by dakk** [comment]
travis is enabled for this repo, it's not clear why it doesn't display travis info on github (https://travis-ci.org/github/dakk/secp256k1-ml/pull_requests)

**Comment by anton-trunov** [comment]
Indeed, strange. I think it’s the first time I see this.
Anyways, thanks for merging.

**Comment by dakk** [comment]
thank you for the contribution, I add you on authors; are you using this library in one of your project?

**Comment by anton-trunov** [comment]
Thank you, I appreciate that.

Yes, my coworkers and I are using the library to implement cryptographic builtins for our System F-based intermediate-level smart contract language Scilla: https://scilla-lang.org.

**Pull request merged**
