### PR TITLE
switch to jbuilder

### PR DESCRIPTION
**Pull request by vbmithr**

### CODE REVIEW

**Comment by dakk** [comment]
Hi, thank you for this pull; can you please provide me some info about jbuilder and why it's better than oasis?

**Comment by vbmithr** [comment]
Not ready yet.

**Comment by vbmithr** [comment]
You can pull this first if you like.

But I am rewriting much of it, anyway, I'll make a second PR later.

**Comment by dakk** [comment]
Ok, I'll try and check it asap, thanks

**Comment by dakk** [comment]
Hi; I'm trying the jbuilder pull req but when I try to "make":

```
dakk ~/secjbuild make
jbuilder build @install @runtest
Error: External library "base" not found.
-> required by "src/config/jbuild (context default)"
Hint: try: jbuilder external-lib-deps --missing @install @runtest
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 1
```

then I tried:
```
dakk ~/secjbuild jbuilder external-lib-deps --missing @install @runtest
Error: The following required libraries are missing in the default context:
- base
- configurator
- stdio
Hint: try: opam install base configurator stdio

```

so I tried:
```
dakk ~/secjbuild opam install base configurator stdio
The following dependencies couldn't be met:
  - conduit -> logs >= 0.5.0
Your request can't be satisfied:
  - No package matches logs>=0.5.0.

No solution found, exiting
```

Can you please explain me how to setup deps? And these deps are because of jbuilder, right?

**Comment by dakk** [comment]
My bad, I was using an outdated env; this jbuilder is amazing, thank you for proposing this pull.

**Pull request merged**
